version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'teste123'
      MYSQL_ROOT_PASSWORD: 'teste123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  redis:
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: redis_pass
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
    ports:
      - "6379:6379"
    restart: on-failure
    networks:
      - java_network
    tty: true